#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Dec 31 19:00:10 2023

@author: jairoescrito
"""

from datetime import datetime
from dateutil.relativedelta import relativedelta
import pandas as pd

edad = relativedelta(datetime.now(), datetime(1983, 2, 11))

edad.years



fecha_nacimiento = datetime.strptime("11/02/1983", "%d/%m/%Y")
edad = relativedelta(datetime.now(), fecha_nacimiento)
edad.years


variables = estudiantes.columns
